import "../styles/globals.scss";
import { Inter, Raleway } from "next/font/google";
import Navigation from "@/components/layout/Navigation";
import Footer from "@/components/layout/Footer";
import PageContainer from "@/components/layout/PageContainer";
import Provider from "@/redux/Provider";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Arnolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      style={{
        colorScheme: "dark !important",
      }}
    >
      <head>
        {/* light logo */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/arnolio-logo-light/apple-touch-icon.png"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/arnolio-logo-light/favicon-32x32.png"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/arnolio-logo-light/favicon-16x16.png"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="manifest"
          href="/arnolio-logo-light/site.webmanifest"
          media="(prefers-color-scheme: light)"
        />
        {/* dark logo */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/arnolio-logo-dark/apple-touch-icon.png"
          media="(prefers-color-scheme: dark)"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/arnolio-logo-dark/favicon-32x32.png"
          media="(prefers-color-scheme: dark)"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/arnolio-logo-dark/favicon-16x16.png"
          media="(prefers-color-scheme: dark)"
        />
        <link
          rel="manifest"
          href="/arnolio-logo-dark/site.webmanifest"
          media="(prefers-color-scheme: dark)"
        />
      </head>
      <body className={inter.className}>
        <Provider>
          <Navigation />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
